### ISSUE TITLE
common.sh has wrong ${VKCDemos_src}

### ISSUE THREAD

**Issue by choconnit** [scottalmond/VKCDemos#1]
Hi Scott,

For scripts/mlx90640_install.sh to work, I had to change line 9 in common.sh to
: ${VKCDemos_src:=/home/pi/Documents/VKCDemos}

dtt

**Comment by stochswarm** [comment]
`VKCDemos_src` is just the location to the git repo; so, it is to wherever you do a `git clone ...` from. I figured the default would be `~/src/VKCDemos` It could be set differently. The idea was, to run it as:
```bash
$ VKCDemos_src=/home/pi/Documents/VKCDemos scripts/mlx90640_install.sh
```
and that will override the default value. This is the same with any of the `": ${var:=...}"` bits in there. If it should be updated, it should be to something more generic:
```bash
...
: ${VKCDemos_src:="$(dirname "$(dirname "$(readlink -f "$0")")")"}
...
```
see 5c79a8a817731e3b20bff98653df76e5fc8c2b96
